name: Fly Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Deploy to Fly
        uses: superfly/fly-deploy@v0
        with:
          args: "--local-only --ha=false"
          remote-only: false
          build: true
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}