spring:
  application:
    name: bookbook
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${bed1439fab95efaac2f73bdf322a6636}
            client-secret: ${zKnaoCDMy4zpdMVQavHjs7bebwSpgjqd}
            scope: profile, account_email
            redirect-uri: "http://localhost:8080/bookbook/login/oauth2/code/kakao"
            client-name: KAKAO
            client-authentication-method: post
            authorization-grant-type: authorization_code
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.bookbook: DEBUG