spring:
  application:
    name: bookbook
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  servlet:
    multipart:
      max-file-size: 10MB      # 개별 파일 크기 제한
      max-request-size: 50MB   # 전체 요청 크기 제한
      location: uploads
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: KAKAO
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
          naver:
            client-id: ${NAVER_API_KEY}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Naver
            authorization-grant-type: authorization_code
          google:
            client-id: ${GOOGLE_API_KEY}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
            authorization-grant-type: authorization_code
        provider:
            kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize
                token-uri: https://kauth.kakao.com/oauth/token
                user-info-uri: https://kapi.kakao.com/v2/user/me
                user-name-attribute: id
            naver:
                authorization-uri: https://nid.naver.com/oauth2.0/authorize
                token-uri: https://nid.naver.com/oauth2.0/token
                user-info-uri: https://openapi.naver.com/v1/nid/me
                user-name-attribute: response
            google:
                authorization-uri: https://accounts.google.com/o/oauth2/auth
                token-uri: https://oauth2.googleapis.com/token
                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                user-name-attribute: sub
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.bookbook: DEBUG
frontend:
  base-url: http://localhost:3000
  signup-path: /bookbook/user/signup
  main-path: /bookbook
aladin:
  ttbkey: ${ALADIN_API_KEY}
jwt:
  secret-key: YourSuperSecretKeyForJWTGenerationAndValidationThatShouldBeAtLeast256BitsLongAndRandomlyGenerated
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
  cookie:
    name: JWT_TOKEN
    refresh-name: "refreshToken"
