import { WishListItem } from './types';

export const dummyWishList: WishListItem[] = [
    {
        id: 1,
        rentId: 101,
        title: '한강 작가 책입니다. 추천!',
        bookTitle: '작별하지 않는다',
        bookAuthor: '한강',
        bookPublisher: '문학동네',
        bookCondition: '양호',
        rentStatus: 'Available',
        lenderUserId: 201,
        lenderUserName: '김민수',
        lenderNickname: '책벌레',
        bookImage: '/book-sample-1.png',
        createDate: '2024-01-15T10:30:00',
        address: '서울시 강남구'
    },
    {
        id: 2,
        rentId: 102,
        title: '20년 가까이 숲속 승려 생활을 했던 사람의 인생 이야기',
        bookTitle: '내가 틀릴 수도 있습니다 숲속의 현자가 전하는 마지막 인생',
        bookAuthor: '미욘 나티코 린데벨라드',
        bookPublisher: '다산초당',
        bookCondition: '최상',
        rentStatus: 'Finished',
        lenderUserId: 202,
        lenderUserName: '이영희',
        lenderNickname: '독서광',
        bookImage: '/book-sample-2.png',
        createDate: '2024-01-14T15:20:00',
        address: '서울시 서초구'
    },
    {
        id: 3,
        rentId: 103,
        title: '모든 것은 건너가기 위함입니다. 마음이 편안해지는 책이에요.',
        bookTitle: '건너가는 자 익숙함에서 탁월함으로 얽매임에서 벗어남으로',
        bookAuthor: '최진성',
        bookPublisher: '썸앤파커스',
        bookCondition: '양호',
        rentStatus: 'Loaned',
        lenderUserId: 203,
        lenderUserName: '박지훈',
        lenderNickname: '책방지기',
        bookImage: '/book-sample-3.png',
        createDate: '2024-01-13T09:45:00',
        address: '서울시 마포구'
    },
    {
        id: 4,
        rentId: 104,
        title: '숨기려 했던 역사를 알게 되는 책이에요',
        bookTitle: '소년이 온다',
        bookAuthor: '한강',
        bookPublisher: '창비',
        bookCondition: '보통',
        rentStatus: 'Available',
        lenderUserId: 204,
        lenderUserName: '최서연',
        lenderNickname: '문학소녀',
        bookImage: '/book-sample-4.png',
        createDate: '2024-01-12T14:10:00',
        address: '서울시 송파구'
    },
    {
        id: 5,
        rentId: 105,
        title: '내 슬픔도 타인의 슬픔도 배우게 돼요.',
        bookTitle: '슬픔을 공부하는 슬픔',
        bookAuthor: '신형철',
        bookPublisher: '한겨레출판',
        bookCondition: '최상',
        rentStatus: 'Available',
        lenderUserId: 205,
        lenderUserName: '정다은',
        lenderNickname: '시인',
        bookImage: '/book-sample-5.png',
        createDate: '2024-01-11T11:55:00',
        address: '서울시 종로구'
    },
    {
        id: 6,
        rentId: 106,
        title: '믿고 읽는 한강 작가',
        bookTitle: '작별하지 않는다',
        bookAuthor: '한강',
        bookPublisher: '문학동네',
        bookCondition: '양호',
        rentStatus: 'Available',
        lenderUserId: 206,
        lenderUserName: '강준호',
        lenderNickname: '책사랑',
        bookImage: '/book-sample-1.png',
        createDate: '2024-01-10T16:30:00',
        address: '서울시 성북구'
    },
    {
        id: 7,
        rentId: 107,
        title: '현재의 힘듬을 내려놓게 해줍니다.',
        bookTitle: '내가 틀릴 수도 있습니다 숲속의 현자가 전하는 마지막 인생',
        bookAuthor: '미욘 나티코 린데별라드',
        bookPublisher: '다산초당',
        bookCondition: '최상',
        rentStatus: 'Loaned',
        lenderUserId: 207,
        lenderUserName: '송미라',
        lenderNickname: '독서매니아',
        bookImage: '/book-sample-2.png',
        createDate: '2024-01-09T13:25:00',
        address: '서울시 용산구'
    },
    {
        id: 8,
        rentId: 108,
        title: '모든 것은 아제아제 바라아제 바라승아제 모지 사바하',
        bookTitle: '건너가는 자 익숙함에서 탁월함으로 얽매임에서 벗어남으로',
        bookAuthor: '최진성',
        bookPublisher: '썸앤파커스',
        bookCondition: '양호',
        rentStatus: 'Loaned',
        lenderUserId: 208,
        lenderUserName: '한지우',
        lenderNickname: '지식탐험가',
        bookImage: '/book-sample-3.png',
        createDate: '2024-01-08T10:15:00',
        address: '서울시 강동구'
    }
];