import { MyBook } from './types';

export const dummyLendListBooks: MyBook[] = [
  {
    id: 1,
    lenderUserId: 1,
    title: "IT 전공서적 대여합니다",
    bookTitle: "클린 코드",
    author: "로버트 C. 마틴",
    publisher: "인사이트",
    category: "컴퓨터/IT",
    bookCondition: "상",
    bookImage: "https://image.yes24.com/goods/11681152/XL",
    address: "서울특별시 강남구",
    contents: "깨끗한 코드 작성법을 배울 수 있는 필독서입니다. 거의 새책 수준입니다.",
    rentStatus: "대여가능",
    createdDate: "2024-01-15T10:30:00",
    modifiedDate: "2024-01-15T10:30:00"
  },
  {
    id: 2,
    lenderUserId: 1,
    title: "자바 교재 대여",
    bookTitle: "이펙티브 자바 3판",
    author: "조슈아 블로크",
    publisher: "인사이트",
    category: "컴퓨터/IT",
    bookCondition: "중",
    bookImage: "https://image.yes24.com/goods/65551284/XL",
    address: "서울특별시 서초구",
    contents: "자바 개발자 필수 도서입니다. 약간의 필기 흔적이 있습니다.",
    rentStatus: "대여중",
    returnDate: "2024-02-10T14:00:00",
    createdDate: "2024-01-10T14:20:00",
    modifiedDate: "2024-01-12T09:15:00"
  },
  {
    id: 3,
    lenderUserId: 1,
    title: "한강 작가 소설 대여",
    bookTitle: "작별하지 않는다",
    author: "한강",
    publisher: "문학동네",
    category: "소설",
    bookCondition: "양호",
    bookImage: "/book-sample-1.png",
    address: "서울특별시 종로구",
    contents: "한강 작가의 감동적인 신작입니다.",
    rentStatus: "대여가능",
    createdDate: "2024-01-18T11:20:00",
    modifiedDate: "2024-01-18T11:20:00"
  },
  {
    id: 4,
    lenderUserId: 1,
    title: "인생 철학서 대여합니다",
    bookTitle: "내가 틀릴 수도 있습니다",
    author: "미욘 나티코 린데별라드",
    publisher: "다산초당",
    category: "인문",
    bookCondition: "최상",
    bookImage: "/book-sample-2.png",
    address: "서울특별시 강북구",
    contents: "숲속의 현자가 전하는 지혜로운 인생 이야기",
    rentStatus: "대여중",
    returnDate: "2024-02-05T15:00:00",
    createdDate: "2024-01-17T14:30:00",
    modifiedDate: "2024-01-19T10:20:00"
  },
  {
    id: 5,
    lenderUserId: 1,
    title: "자기계발서 나눔",
    bookTitle: "건너가는 자",
    author: "최진성",
    publisher: "썸앤파커스",
    category: "자기계발",
    bookCondition: "양호",
    bookImage: "/book-sample-3.png",
    address: "서울특별시 은평구",
    contents: "익숙함에서 탁월함으로 나아가는 방법을 알려줍니다.",
    rentStatus: "대여가능",
    createdDate: "2024-01-16T09:15:00",
    modifiedDate: "2024-01-16T09:15:00"
  },
  {
    id: 6,
    lenderUserId: 1,
    title: "스프링 부트 실습서",
    bookTitle: "스프링 부트와 AWS로 혼자 구현하는 웹 서비스",
    author: "이동욱",
    publisher: "프리렉",
    category: "컴퓨터/IT",
    bookCondition: "상",
    bookImage: "https://image.yes24.com/goods/83849117/XL",
    address: "서울특별시 동대문구",
    contents: "실무에서 바로 사용할 수 있는 스프링 부트 프로젝트 가이드",
    rentStatus: "대여중",
    returnDate: "2024-02-08T12:00:00",
    createdDate: "2024-01-13T13:25:00",
    modifiedDate: "2024-01-15T11:10:00"
  },
  {
    id: 7,
    lenderUserId: 1,
    title: "한강 작가 대표작",
    bookTitle: "소년이 온다",
    author: "한강",
    publisher: "창비",
    category: "소설",
    bookCondition: "보통",
    bookImage: "/book-sample-4.png",
    address: "서울특별시 중랑구",
    contents: "5.18 광주 민주화 운동을 다룬 감동적인 소설입니다.",
    rentStatus: "대여가능",
    createdDate: "2024-01-12T10:50:00",
    modifiedDate: "2024-01-12T10:50:00"
  },
  {
    id: 8,
    lenderUserId: 1,
    title: "에세이 대여합니다",
    bookTitle: "슬픔을 공부하는 슬픔",
    author: "신형철",
    publisher: "한겨레출판",
    category: "에세이",
    bookCondition: "최상",
    bookImage: "/book-sample-5.png",
    address: "서울특별시 광진구",
    contents: "문학평론가의 깊이 있는 에세이입니다.",
    rentStatus: "대여가능",
    createdDate: "2024-01-11T15:35:00",
    modifiedDate: "2024-01-11T15:35:00"
  },
  {
    id: 9,
    lenderUserId: 1,
    title: "디자인 패턴 교재",
    bookTitle: "GoF의 디자인 패턴",
    author: "에리히 감마",
    publisher: "프로텍미디어",
    category: "컴퓨터/IT",
    bookCondition: "양호",
    bookImage: "https://image.yes24.com/goods/17525598/XL",
    address: "서울특별시 송파구",
    contents: "객체지향 설계의 바이블입니다.",
    rentStatus: "finished",
    hasReview: false,
    createdDate: "2024-01-08T09:30:00",
    modifiedDate: "2024-01-25T16:20:00"
  },
  {
    id: 10,
    lenderUserId: 1,
    title: "데이터베이스 교재",
    bookTitle: "데이터베이스 시스템의 개념 및 응용",
    author: "엘마스리",
    publisher: "피어슨",
    category: "컴퓨터/IT",
    bookCondition: "중",
    bookImage: "https://image.yes24.com/goods/2732189/XL",
    address: "서울특별시 관악구",
    contents: "데이터베이스 이론과 실무를 다룬 교재입니다.",
    rentStatus: "finished",
    hasReview: true,
    createdDate: "2024-01-07T13:40:00",
    modifiedDate: "2024-01-20T11:30:00"
  },
  {
    id: 11,
    lenderUserId: 1,
    title: "웹 개발 관련 서적",
    bookTitle: "모던 자바스크립트 Deep Dive",
    author: "이웅모",
    publisher: "위키북스",
    category: "컴퓨터/IT",
    bookCondition: "상",
    bookImage: "https://image.yes24.com/goods/92742567/XL",
    address: "서울특별시 마포구",
    contents: "자바스크립트를 깊이 있게 학습하고 싶은 분들께 추천합니다.",
    rentStatus: "대여가능",
    createdDate: "2024-01-20T16:45:00",
    modifiedDate: "2024-01-20T16:45:00"
  }
];